In [1]:
import torch
import numpy as np

### 1.tensor的数据类型：torch.FloatTensor,torch.IntTensor,torch.ByteTensor
    type()是python中，显示是个tenor类型，不能显示是tensor的什么类型

In [9]:
a = torch.randn(2,3)
print(a)
print(type(a))
print(a.type())
print(isinstance(a, torch.FloatTensor))

tensor([[ 0.3273, -0.0621,  1.5318],
        [ 0.5324, -1.5384, -0.2168]])
<class 'torch.Tensor'>
torch.FloatTensor
True


分cpu tensor和gpu tensor，两者类型不同

In [11]:
a = a.cuda()
print(a.type())

torch.cuda.FloatTensor


### 2 tensor的维度
#### 2.1 标量的表示：0维度的tensor——用来表示loss
    
    size和shape表示tensor的形状（大小），其长度表示维度，并表示每一维的模大小。
    .shape没有括号（静态方法），.size()（一般方法）要有括号

In [24]:
s = torch.tensor(1.5)
print(s)
print(s.shape)
print(len(s.shape))
print(type(s.shape))
print(s.size())

tensor(1.5000)
torch.Size([])
0
<class 'torch.Size'>
torch.Size([])


#### 2.2 一维tensor——用来表示偏置b
    中括号数代表维数，torch.FloatTensor(2) 正太随机随机生成2维tensor

In [98]:
b = torch.tensor([2.2])
b2 = torch.tensor([1.2, 3.4, 5.2])
print(b, b2)
torch.FloatTensor(2)

tensor([2.2000]) tensor([1.2000, 3.4000, 5.2000])


tensor([-1.6297])

In [44]:
a = torch.randn(6)
a

tensor([ 0.3045, -1.3696, -0.0406,  0.9082, -0.1377,  0.1557])

In [48]:
a2=a[2]
a2.type()
a2.shape

torch.Size([])

In [90]:
data = np.ones([2])
data

array([1., 1.])

In [93]:
d = torch.from_numpy(data)

In [95]:
d[1]

tensor(1., dtype=torch.float64)

#### 2.3 二维tensor

In [51]:
a = torch.randn(2, 3)
print(a)
print(a.shape)
print(a.size())

tensor([[ 2.0243, -0.8503, -1.9563],
        [ 1.4240, -0.8669, -2.1819]])
torch.Size([2, 3])
torch.Size([2, 3])


In [20]:
a.size(0)

2

In [18]:
a.size(1)

3

In [26]:
a.shape[0]

2

In [53]:
a1=a[1]
print(a1)

tensor(-0.8669)


#### 2.4 三维tensor

In [74]:
a = torch.randn(3,2,4)
a

tensor([[[ 0.6365, -0.8727, -0.2060, -0.3643],
         [-0.5589, -0.5231, -1.7552,  1.8530]],

        [[ 1.7872,  0.1496,  1.2326,  0.6848],
         [-1.0140,  0.8296, -1.5323,  0.7569]],

        [[-0.0615,  2.6354,  1.7104,  1.7122],
         [ 0.0888, -0.1525,  0.2113,  0.9242]]])

In [35]:
list(a.shape)

[3, 2, 4]

In [40]:
list(a.size())

[3, 2, 4]

In [55]:
a[1]

tensor([[ 0.7011, -2.5293,  1.2249, -1.9823],
        [-0.2106, -0.3113, -0.3635, -0.3062]])

In [75]:
a[1,0]

tensor([1.7872, 0.1496, 1.2326, 0.6848])

In [76]:
a[1,0,1]

tensor(0.1496)

#### 2.5 四维tensor

In [77]:
a = torch.randn(2,3,4,4)

第一维度含有2个分量，每个分量是(3,4,4);
第二维度含有3个分量，每个分量是(4,4);
后两个维度可以看成2维数据。

多个维度可以看做对低维度的分组。图可表示两个样本（第一维度），三个通道（第二维度），4×4的图片

<img src="tu.jpg" width="50%">

In [78]:
a

tensor([[[[-0.6781, -0.4027, -0.2729, -0.3540],
          [-1.0817,  0.0913, -0.5199,  1.9542],
          [-0.3900, -0.7917, -0.1190, -0.7608],
          [-0.2716, -0.8781, -0.1732,  2.0854]],

         [[-0.3177,  0.4616, -0.7909, -0.5014],
          [ 0.3403, -1.7797,  0.4540, -0.6077],
          [ 0.9412,  0.4109, -2.3087,  0.4900],
          [-1.1505,  0.6399, -0.4708,  0.3097]],

         [[ 0.9105, -0.3403,  1.3837,  1.4753],
          [ 0.4124,  0.3156, -0.1722,  0.3705],
          [ 0.2299, -0.6531,  1.7819,  0.4144],
          [ 0.4459, -0.1142, -1.0165,  0.8772]]],


        [[[-1.3322,  0.1717,  0.3931,  0.0851],
          [ 2.5856, -0.1840,  1.3580,  0.2227],
          [ 0.2393,  0.1902,  1.6123, -1.7654],
          [-0.0560,  0.3734, -0.5461,  1.3909]],

         [[ 0.4368,  1.6213,  1.7320, -1.0062],
          [ 1.2812, -0.0808,  0.2388, -0.6505],
          [ 1.6410,  0.6433, -0.9596,  0.1446],
          [ 0.9391, -0.8427,  0.8361,  1.1164]],

         [[ 0.4402, -0.1852,

这样的取法是1,3,4维度为定值，2维度所有值输出，2维度长度为3，因此为长度为3的一维tensor

In [85]:
a[0,:,1,1]

tensor([ 0.0913, -1.7797,  0.3156])

In [84]:
a[:,0,0,0]

tensor([-0.6781, -1.3322])

In [89]:
a[:,:,1,2]

tensor([[-0.5199,  0.4540, -0.1722],
        [ 1.3580,  0.2388, -2.6883]])

In [80]:
a[0,:,:,:]

tensor([[[-0.6781, -0.4027, -0.2729, -0.3540],
         [-1.0817,  0.0913, -0.5199,  1.9542],
         [-0.3900, -0.7917, -0.1190, -0.7608],
         [-0.2716, -0.8781, -0.1732,  2.0854]],

        [[-0.3177,  0.4616, -0.7909, -0.5014],
         [ 0.3403, -1.7797,  0.4540, -0.6077],
         [ 0.9412,  0.4109, -2.3087,  0.4900],
         [-1.1505,  0.6399, -0.4708,  0.3097]],

        [[ 0.9105, -0.3403,  1.3837,  1.4753],
         [ 0.4124,  0.3156, -0.1722,  0.3705],
         [ 0.2299, -0.6531,  1.7819,  0.4144],
         [ 0.4459, -0.1142, -1.0165,  0.8772]]])

In [81]:
a[0,0,:,:]

tensor([[-0.6781, -0.4027, -0.2729, -0.3540],
        [-1.0817,  0.0913, -0.5199,  1.9542],
        [-0.3900, -0.7917, -0.1190, -0.7608],
        [-0.2716, -0.8781, -0.1732,  2.0854]])

In [82]:
a[0,0,:,0]

tensor([-0.6781, -1.0817, -0.3900, -0.2716])

In [86]:
a.dim()

4

In [87]:
a.numel()

96

### 总结

    (设a为tensor)
    
    1. a.type()  type(a)
    2. torch.tensor([[1,2,3],[3,4,5]])    torch.randn(2,3)(不能生成标量-0维度，最低1维)
    3. a.shape，  a.size()，  a.shape[0]，  a.size(1)，  list(a.shape)， a.dim(),  a.numel()
    4. torch.from_numpy(a)
    5. 4维数据的理解，低维度的分组，以2维图像为低维度基本单元；提取某一维度。